version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    cooldown:
      default-days: 7
    labels: ["autoupdate"]
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    cooldown:
      default-days: 7
    labels: ["autoupdate"]
    groups:
      pre-commit:
        patterns: ["*"]
