version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels: ["autoupdate"]
    groups:
      github-actions:
        patterns: ["*"]

  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels: ["autoupdate"]
    groups:
      pre-commit:
        patterns: ["*"]
