[build-system]
build-backend = "scikit_build_core.build"
requires = [
  # TODO: keep in sync with [project.dependencies]
  "scikit-build-core>=0.11",
  "setuptools-scm>=8",
  "cython>=3.1.0",
  "cython-cmake>=0.2",
  "numpy >=1.26.0"
]

[project]
authors = [{ name = "Intel Corporation", email = "scripting@intel.com" }]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Programming Language :: C",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Free Threading :: 2 - Beta",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
  "Operating System :: Microsoft :: Windows",
  "Operating System :: POSIX :: Linux",
  "Operating System :: POSIX",
  "Operating System :: Unix"
]
dependencies = [
  # TODO: keep in sync with [build-system.requires] and /conda-recipe/meta.yaml
  # This restrictions are for dependabot, actual restrictions are set with
  # conda.
  # TODO: populate it during build process
  # TODO: do we have to set sycl runtime dependencies here
  # "dpcpp-cpp-rt>=0.59.0",
  # "intel-cmplr-lib-rt>=0.59.0"
  "numpy>=2.0.0"
]
description = "A lightweight Python wrapper for a subset of SYCL."
dynamic = ["version"]
keywords = [
  "dpctl",
  "intel",
  "oneapi",
  "dpcpp"
]
license = "Apache-2.0"
name = "dpctl"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"

[project.optional-dependencies]
benchmark = ["asv>=0.6", "numpy"]
coverage = ["Cython>=3.1.0", "pytest", "coverage", "tomli"]
docs = [
  "Cython>=3.1.0",
  "graphviz",
  "pydot",
  "furo",
  "sphinx",
  "sphinx-copybutton",
  "sphinx-design",
  "sphinxcontrib-googleanalytics",
  "sphinxcontrib-jsmath",
  "sphinxcontrib-programoutput",
  "sphinxcontrib-spelling"
]

[project.urls]
Changelog = "https://github.com/IntelPython/dpctl/blob/master/CHANGELOG.md"
Documentation = "https://intelpython.github.io/dpctl/"
Homepage = "https://github.com/IntelPython/dpctl"
Issues = "https://github.com/IntelPython/dpctl/issues"
Repository = "https://github.com/IntelPython/dpctl.git"

[tool.black]
line-length = 80

[tool.codespell]
builtin = "clear,rare,informal,names"
check-filenames = true
ignore-words-list = "nd"
quiet-level = 3

[tool.coverage.report]
omit = [
  "dpctl/tests/*",
  "dpctl/_version.py",
  "*/_cython_api*/stringsource"
]

[tool.coverage.run]
branch = true
omit = [
  "dpctl/tests/*",
  "dpctl/_version.py",
  "*/_cython_api*/stringsource"
]
plugins = [
  "Cython.Coverage"
]
source = [
  "dpctl"
]

[tool.cython-lint]
max-line-length = 80

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 80
multi_line_output = 3
use_parentheses = true

[tool.pytest.ini_options]
addopts = [
  "--junitxml=junit.xml",
  "--ignore=run_test.py",
  "--tb=native",
  "--strict-markers",
  "--durations=20",
  "-q",
  "-ra"
]
markers = [
  "broken_complex: mark a test that is skipped due to complex implementation issues in DPC++ compiler"
]
minversion = "6.0"
norecursedirs = [
  ".*",
  "*.egg*",
  "build",
  "dist",
  "conda-recipe"
]

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
metadata.version.provider = "scikit_build_core.metadata.setuptools_scm"
minimum-version = "build-system.requires"
sdist.include = [
  "dpctl/apis/include/*.h",
  "dpctl/tests/_c_ext.c"
]
wheel.exclude = [
  "dpctl/**/CMakeLists.txt",
  "dpctl/**/*.pyx",
  "!dpctl/tests/*.pyx",
  "dpctl/**/*.pxi",
  "dpctl/**/*.hpp",
  "!dpctl/include/**",
  "dpctl/.gitignore",
  "dpctl/apis/",
  "dpctl/utils/src/"
]
wheel.packages = ["dpctl"]

[[tool.scikit-build.generate]]
path = "dpctl/_version.py"
template = '''
__version__ = version = "${version}"
'''

[tool.setuptools_scm]
