numpy:
    - '1.23'
c_compiler:                   # [linux]
    - gcc                     # [linux]
cxx_compiler:                 # [linux]
    - gxx                     # [linux]
cxx_compiler_version:         # [linux]
    - '14'                    # [linux]
c_stdlib:                     # [linux]
    - sysroot                 # [linux]
c_stdlib_version:             # [linux]
    - '2.28'                  # [linux]
c_stdlib:                     # [win]
    - vs                      # [win]
cxx_compiler:                 # [win]
    - vs2022                  # [win]
c_compiler:                   # [win]
    - vs2022                  # [win]
