{% set name = "pydppl" %}

package:
    name: {{ name|lower }}
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ..

build:
    number: 0
    script_env:
        - ONEAPI_ROOT

requirements:
    build:
        - {{ compiler('cxx') }}
    host:
        - setuptools
        - cffi >=1.0.0
        - cython
        - cmake
        - python
        - make  # [unix]
        - ninja  # [win]
        - numpy >=1.17
    run:
        - python
        - numpy >=1.17
        - cffi >=1.0.0

about:
    home: https://github.com/IntelPython/PyDPPL.git
    summary: 'A lightweight Python wrapper for a subset of OpenCL and SYCL API.'

extra:
    recipe-maintainers:
        - diptorup deb
        - PokhodenkoSA
