package:
    name: dpctl
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ..

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
        - ONEAPI_ROOT              # for wheel on Linux
        - WHEELS_OUTPUT_FOLDER

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('dpcpp') }}  # [not osx]
    host:
        - setuptools
        - cython
        - cmake  >=3.21
        - python
        - ninja
        - scikit-build
        - numpy 1.19
        - wheel
    run:
        - python
        - {{ pin_compatible('numpy') }}
        - dpcpp-cpp-rt >=2022.0

test:
    requires:
        - cython
        - pytest
        - pytest-cov

about:
    home: https://github.com/IntelPython/dpctl.git
    license: Apache-2.0
    license_file: LICENSE
    summary: 'A lightweight Python wrapper for a subset of SYCL API.'
    description: |
        <strong>LEGAL NOTICE:  Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://opensource.org/licenses/Apache-2.0" target="_blank">Apache-2.0</a>
        <br/><br/>

extra:
    recipe-maintainers:
        - diptorup deb
        - PokhodenkoSA
