var files_dup =
[
    [ "CBindingWrapping.h", "d1/d38/CBindingWrapping_8h.html", "d1/d38/CBindingWrapping_8h" ],
    [ "DllExport.h", "d6/d26/DllExport_8h.html", "d6/d26/DllExport_8h" ],
    [ "dpctl_data_types.h", "dd/d1c/dpctl__data__types_8h.html", "dd/d1c/dpctl__data__types_8h" ],
    [ "dpctl_sycl_context_interface.cpp", "d4/d08/dpctl__sycl__context__interface_8cpp.html", "d4/d08/dpctl__sycl__context__interface_8cpp" ],
    [ "dpctl_sycl_context_interface.h", "df/d74/dpctl__sycl__context__interface_8h.html", "df/d74/dpctl__sycl__context__interface_8h" ],
    [ "dpctl_sycl_device_interface.cpp", "de/dc3/dpctl__sycl__device__interface_8cpp.html", "de/dc3/dpctl__sycl__device__interface_8cpp" ],
    [ "dpctl_sycl_device_interface.h", "d4/d5a/dpctl__sycl__device__interface_8h.html", "d4/d5a/dpctl__sycl__device__interface_8h" ],
    [ "dpctl_sycl_enum_types.h", "d3/d94/dpctl__sycl__enum__types_8h.html", "d3/d94/dpctl__sycl__enum__types_8h" ],
    [ "dpctl_sycl_event_interface.cpp", "db/dcc/dpctl__sycl__event__interface_8cpp.html", "db/dcc/dpctl__sycl__event__interface_8cpp" ],
    [ "dpctl_sycl_event_interface.h", "d5/d12/dpctl__sycl__event__interface_8h.html", "d5/d12/dpctl__sycl__event__interface_8h" ],
    [ "dpctl_sycl_kernel_interface.cpp", "d1/ddb/dpctl__sycl__kernel__interface_8cpp.html", "d1/ddb/dpctl__sycl__kernel__interface_8cpp" ],
    [ "dpctl_sycl_kernel_interface.h", "df/df4/dpctl__sycl__kernel__interface_8h.html", "df/df4/dpctl__sycl__kernel__interface_8h" ],
    [ "dpctl_sycl_platform_interface.cpp", "d5/da7/dpctl__sycl__platform__interface_8cpp.html", "d5/da7/dpctl__sycl__platform__interface_8cpp" ],
    [ "dpctl_sycl_platform_interface.h", "d3/d02/dpctl__sycl__platform__interface_8h.html", "d3/d02/dpctl__sycl__platform__interface_8h" ],
    [ "dpctl_sycl_program_interface.cpp", "db/de0/dpctl__sycl__program__interface_8cpp.html", "db/de0/dpctl__sycl__program__interface_8cpp" ],
    [ "dpctl_sycl_program_interface.h", "dc/d02/dpctl__sycl__program__interface_8h.html", "dc/d02/dpctl__sycl__program__interface_8h" ],
    [ "dpctl_sycl_queue_interface.cpp", "d3/daf/dpctl__sycl__queue__interface_8cpp.html", "d3/daf/dpctl__sycl__queue__interface_8cpp" ],
    [ "dpctl_sycl_queue_interface.h", "da/db8/dpctl__sycl__queue__interface_8h.html", "da/db8/dpctl__sycl__queue__interface_8h" ],
    [ "dpctl_sycl_queue_manager.cpp", "d2/db7/dpctl__sycl__queue__manager_8cpp.html", "d2/db7/dpctl__sycl__queue__manager_8cpp" ],
    [ "dpctl_sycl_queue_manager.h", "d1/dac/dpctl__sycl__queue__manager_8h.html", "d1/dac/dpctl__sycl__queue__manager_8h" ],
    [ "dpctl_sycl_types.h", "df/d57/dpctl__sycl__types_8h.html", "df/d57/dpctl__sycl__types_8h" ],
    [ "dpctl_sycl_usm_interface.cpp", "d1/de8/dpctl__sycl__usm__interface_8cpp.html", "d1/de8/dpctl__sycl__usm__interface_8cpp" ],
    [ "dpctl_sycl_usm_interface.h", "de/d29/dpctl__sycl__usm__interface_8h.html", "de/d29/dpctl__sycl__usm__interface_8h" ],
    [ "dpctl_utils.cpp", "d7/d8c/dpctl__utils_8cpp.html", "d7/d8c/dpctl__utils_8cpp" ],
    [ "dpctl_utils.h", "da/d48/dpctl__utils_8h.html", "da/d48/dpctl__utils_8h" ],
    [ "dpctl_utils_helper.cpp", "d3/d5b/dpctl__utils__helper_8cpp.html", "d3/d5b/dpctl__utils__helper_8cpp" ],
    [ "dpctl_utils_helper.h", "d4/d3f/dpctl__utils__helper_8h.html", "d4/d3f/dpctl__utils__helper_8h" ],
    [ "ExternC.h", "d2/d0a/ExternC_8h.html", "d2/d0a/ExternC_8h" ],
    [ "MemOwnershipAttrs.h", "d4/d8c/MemOwnershipAttrs_8h.html", "d4/d8c/MemOwnershipAttrs_8h" ]
];