var files_dup =
[
    [ "CBindingWrapping.h", "d1/d38/CBindingWrapping_8h.html", "d1/d38/CBindingWrapping_8h" ],
    [ "DllExport.h", "d6/d26/DllExport_8h.html", "d6/d26/DllExport_8h" ],
    [ "dppl_data_types.h", "d4/dcc/dppl__data__types_8h.html", "d4/dcc/dppl__data__types_8h" ],
    [ "dppl_sycl_context_interface.cpp", "dd/d48/dppl__sycl__context__interface_8cpp.html", "dd/d48/dppl__sycl__context__interface_8cpp" ],
    [ "dppl_sycl_context_interface.h", "d8/d8e/dppl__sycl__context__interface_8h.html", "d8/d8e/dppl__sycl__context__interface_8h" ],
    [ "dppl_sycl_device_interface.cpp", "d9/dba/dppl__sycl__device__interface_8cpp.html", "d9/dba/dppl__sycl__device__interface_8cpp" ],
    [ "dppl_sycl_device_interface.h", "d8/d8f/dppl__sycl__device__interface_8h.html", "d8/d8f/dppl__sycl__device__interface_8h" ],
    [ "dppl_sycl_enum_types.h", "d9/d4f/dppl__sycl__enum__types_8h.html", "d9/d4f/dppl__sycl__enum__types_8h" ],
    [ "dppl_sycl_event_interface.cpp", "df/deb/dppl__sycl__event__interface_8cpp.html", "df/deb/dppl__sycl__event__interface_8cpp" ],
    [ "dppl_sycl_event_interface.h", "da/d2c/dppl__sycl__event__interface_8h.html", "da/d2c/dppl__sycl__event__interface_8h" ],
    [ "dppl_sycl_kernel_interface.cpp", "df/dde/dppl__sycl__kernel__interface_8cpp.html", "df/dde/dppl__sycl__kernel__interface_8cpp" ],
    [ "dppl_sycl_kernel_interface.h", "dc/d31/dppl__sycl__kernel__interface_8h.html", "dc/d31/dppl__sycl__kernel__interface_8h" ],
    [ "dppl_sycl_platform_interface.cpp", "d7/d8a/dppl__sycl__platform__interface_8cpp.html", "d7/d8a/dppl__sycl__platform__interface_8cpp" ],
    [ "dppl_sycl_platform_interface.h", "dd/d6a/dppl__sycl__platform__interface_8h.html", "dd/d6a/dppl__sycl__platform__interface_8h" ],
    [ "dppl_sycl_program_interface.cpp", "d0/d52/dppl__sycl__program__interface_8cpp.html", "d0/d52/dppl__sycl__program__interface_8cpp" ],
    [ "dppl_sycl_program_interface.h", "d1/d3d/dppl__sycl__program__interface_8h.html", "d1/d3d/dppl__sycl__program__interface_8h" ],
    [ "dppl_sycl_queue_interface.cpp", "d7/dc5/dppl__sycl__queue__interface_8cpp.html", "d7/dc5/dppl__sycl__queue__interface_8cpp" ],
    [ "dppl_sycl_queue_interface.h", "d4/d7b/dppl__sycl__queue__interface_8h.html", "d4/d7b/dppl__sycl__queue__interface_8h" ],
    [ "dppl_sycl_queue_manager.cpp", "de/d84/dppl__sycl__queue__manager_8cpp.html", "de/d84/dppl__sycl__queue__manager_8cpp" ],
    [ "dppl_sycl_queue_manager.h", "d0/de9/dppl__sycl__queue__manager_8h.html", "d0/de9/dppl__sycl__queue__manager_8h" ],
    [ "dppl_sycl_types.h", "d4/d8f/dppl__sycl__types_8h.html", "d4/d8f/dppl__sycl__types_8h" ],
    [ "dppl_sycl_usm_interface.cpp", "d8/d88/dppl__sycl__usm__interface_8cpp.html", "d8/d88/dppl__sycl__usm__interface_8cpp" ],
    [ "dppl_sycl_usm_interface.h", "dc/d46/dppl__sycl__usm__interface_8h.html", "dc/d46/dppl__sycl__usm__interface_8h" ],
    [ "dppl_utils.cpp", "d4/dfa/dppl__utils_8cpp.html", "d4/dfa/dppl__utils_8cpp" ],
    [ "dppl_utils.h", "dc/d8e/dppl__utils_8h.html", "dc/d8e/dppl__utils_8h" ],
    [ "ExternC.h", "d2/d0a/ExternC_8h.html", "d2/d0a/ExternC_8h" ],
    [ "MemOwnershipAttrs.h", "d4/d8c/MemOwnershipAttrs_8h.html", "d4/d8c/MemOwnershipAttrs_8h" ]
];