# This is a workflow to format Python code with black formatter

name: Code style Python

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The isort jon sort all imports in .py, .pyx, .pyd sources
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: jamescurtin/isort-action@master

  black:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Set up a Python environment for use in actions
      - uses: actions/setup-python@v2

      # Run black code formatter
      - uses: psf/black@20.8b1
        with:
          args: ". --check"
